[tox]
requires =
    tox>=4
env_list = 
    py{312}
    coverage

[testenv]
description = run the tests with pytest
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands = 
    poetry run pytest {posargs:tests}

[mypy]
warn_return_any = True
warn_unused_configs = True

[mypy-photo_sorter]
ignore_missing_imports = True

[testenv:type]
description = run type checks
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands =
    poetry run mypy {posargs:photo_sorter tests}

[testenv:coverage]
description = run coverage report
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands = poetry run pytest --cov-report=html:coverage_report --cov=photo_sorter tests/